{
  "hash": "f1992ec85bfb67f1721e5970b8b1d7ba",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"IBM HR Employee Attrition Analysis: Predictive Modeling for Workforce Retention\"\nsubtitle: \"STAT 515 Final Project\"\nauthor: \"Rutvij & Sean Grieg\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: true\n    code-summary: \"Show Code\"\n    theme: cosmo\n    fig-width: 10\n    fig-height: 7\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n\n\n\n\n# Executive Summary\n\nThis comprehensive statistical analysis investigates the factors contributing to employee attrition using the IBM HR Analytics Employee Attrition & Performance dataset (n=1470). The study addresses three primary research questions using decision trees, random forests, logistic regression with interaction terms, LASSO variable selection, and stratified departmental analysis.\n\n**Key Findings (computed from models below):**\n\n1.  **Work-Life Imbalance:** OverTime is the strongest predictor of attrition. Decision tree analysis identifies high-risk profiles combining overtime work with low tenure.\n\n2.  **Career Stagnation & Compensation:** Years since last promotion increases attrition risk, and LASSO selects the strongest predictors across work-life, pay, and tenure.\n\n3.  **Department-Stratified Satisfaction:** Satisfaction variables show different predictive patterns across departments.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nDataset Overview:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Total Employees: 1470 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Overall Attrition Rate: 16.1 %\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Employees Who Left: 237 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- OverTime Attrition Rate: 30.5 %\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Introduction\n\n## Background\n\nEmployee turnover represents one of the most significant challenges facing modern organizations. Industry estimates suggest replacing an employee can cost a substantial fraction of their annual salary when accounting for recruiting, training, and lost productivity. Understanding the factors that drive employees to leave enables targeted retention strategies before valuable talent departs.\n\nThis analysis leverages the IBM HR Analytics dataset (realistic, simulated dataset commonly used for HR analytics). The dataset contains 1,470 employee records with 39 attributes spanning demographics, job characteristics, satisfaction metrics, and work-life balance indicators.\n\n## Research Questions\n\n<span style=\"color: orange; font-weight: bold;\">An explanation of why these research questions were chosen would be nice</span>\n\n1.  **Work-Life Imbalance & Attrition Risk Profiling:** How do work-life factors (OverTime, DistanceFromHome, WorkLifeBalance, YearsAtCompany) interact to predict attrition, and can we identify distinct \"high-risk\" profiles?\n\n2.  **Career Stagnation & Compensation Effects:** At what thresholds do career stagnation indicators (YearsSinceLastPromotion, YearsInCurrentRole) combined with compensation (MonthlyIncome, PercentSalaryHike) become critical predictors of attrition?\n\n3.  **Department-Stratified Satisfaction Analysis:** Does the predictive power of satisfaction variables (JobSatisfaction, EnvironmentSatisfaction, RelationshipSatisfaction) differ across departments, and which matters most within each?\n\n## Dataset Description\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nDataset Dimensions: 1470 employees, 41 variables\n```\n\n\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Table 1: Key Variables by Research Question</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:left;\"> Description </th>\n   <th style=\"text-align:left;\"> Research Q </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> Attrition </td>\n   <td style=\"text-align:left;width: 60%; \"> Employee left the company (Yes/No) - Response Variable </td>\n   <td style=\"text-align:left;width: 15%; \"> All </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> OverTime </td>\n   <td style=\"text-align:left;width: 60%; \"> Whether employee works overtime (Yes/No) </td>\n   <td style=\"text-align:left;width: 15%; \"> Q1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> DistanceFromHome </td>\n   <td style=\"text-align:left;width: 60%; \"> Distance from home to workplace (miles) </td>\n   <td style=\"text-align:left;width: 15%; \"> Q1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> WorkLifeBalance </td>\n   <td style=\"text-align:left;width: 60%; \"> Work-life balance rating (1-4, higher = better) </td>\n   <td style=\"text-align:left;width: 15%; \"> Q1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> YearsAtCompany </td>\n   <td style=\"text-align:left;width: 60%; \"> Total years at current company </td>\n   <td style=\"text-align:left;width: 15%; \"> Q1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> YearsSinceLastPromotion </td>\n   <td style=\"text-align:left;width: 60%; \"> Years since last promotion </td>\n   <td style=\"text-align:left;width: 15%; \"> Q2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> YearsInCurrentRole </td>\n   <td style=\"text-align:left;width: 60%; \"> Years in current role </td>\n   <td style=\"text-align:left;width: 15%; \"> Q2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> MonthlyIncome </td>\n   <td style=\"text-align:left;width: 60%; \"> Monthly salary </td>\n   <td style=\"text-align:left;width: 15%; \"> Q2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> PercentSalaryHike </td>\n   <td style=\"text-align:left;width: 60%; \"> Percent salary increase </td>\n   <td style=\"text-align:left;width: 15%; \"> Q2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> JobLevel </td>\n   <td style=\"text-align:left;width: 60%; \"> Job level within company hierarchy (1-5) </td>\n   <td style=\"text-align:left;width: 15%; \"> Q2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> JobSatisfaction </td>\n   <td style=\"text-align:left;width: 60%; \"> Job satisfaction rating (1-4) </td>\n   <td style=\"text-align:left;width: 15%; \"> Q3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> EnvironmentSatisfaction </td>\n   <td style=\"text-align:left;width: 60%; \"> Environment satisfaction rating (1-4) </td>\n   <td style=\"text-align:left;width: 15%; \"> Q3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> RelationshipSatisfaction </td>\n   <td style=\"text-align:left;width: 60%; \"> Relationship satisfaction rating (1-4) </td>\n   <td style=\"text-align:left;width: 15%; \"> Q3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 25%; font-weight: bold;\"> Department </td>\n   <td style=\"text-align:left;width: 60%; \"> Department </td>\n   <td style=\"text-align:left;width: 15%; \"> Q3 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Data Exploration and Summary Statistics\n\n## Class Imbalance Analysis\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 1: Attrition Distribution - Class Imbalance](STAT515_HR_Attrition_FIXED_files/figure-html/class-imbalance-1.png){width=960}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nClass Weights for Imbalanced Learning:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Weight for Class 0 (No Attrition): 0.5961 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Weight for Class 1 (Attrition): 3.1013 \n```\n\n\n:::\n:::\n\n\nThe dataset exhibits a significant class imbalance in employee attrition, with 83.9% of employees (1,233) having \"No\" as their attrition value and only 16.1% (237) having \"Yes.\" This imbalance can challenge predictive modeling, as algorithms may be biased toward the majority class. To mitigate this, class weights were calculated inversely proportional to class frequencies, assigning a weight of 0.5961 to the majority class (No attrition) and 3.1013 to the minority class (Yes attrition). These weights can be applied during model training to give greater importance to underrepresented cases, improving the model’s ability to correctly identify employees at risk of leaving.\n\n## Attrition by Key Categorical Variables\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 2: Attrition Rates by Key Categorical Variables](STAT515_HR_Attrition_FIXED_files/figure-html/categorical-eda-1.png){width=960}\n:::\n:::\n\n\nThe graphical analysis suggests that employee attrition varies substantially across several workplace and demographic factors. Employees who work overtime show a markedly higher attrition rate (30.5%) compared to those who do not work overtime (10.4%), indicating overtime may be a strong contributor to turnover. Attrition also differs by department, with Sales experiencing the highest rate (20.6%), followed by HR (19%), while Research & Development has the lowest attrition (13.8%). Marital status appears to be associated with attrition as well, as single employees have a notably higher turnover rate (25.5%) than married (12.5%) or divorced employees (10.1%). Finally, business travel frequency shows a clear pattern: employees who travel frequently have the highest attrition rate (24.9%), followed by those who travel rarely (15%), while non-traveling employees have the lowest attrition (8%). Overall, these graphs indicate that workload demands, job role characteristics, and personal circumstances may play important roles in employee turnover.\n\n## Chi-Square Tests for Categorical Associations\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Table 2: Chi-Square Tests for Categorical Variables</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> χ² </th>\n   <th style=\"text-align:right;\"> df </th>\n   <th style=\"text-align:right;\"> p-value </th>\n   <th style=\"text-align:right;\"> Cramer's V </th>\n   <th style=\"text-align:left;\"> Sig. </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> OverTime </td>\n   <td style=\"text-align:right;\"> 87.56 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 0.0000000 </td>\n   <td style=\"text-align:right;\"> 0.2441 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Department </td>\n   <td style=\"text-align:right;\"> 10.80 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 0.0045256 </td>\n   <td style=\"text-align:right;\"> 0.0857 </td>\n   <td style=\"text-align:left;\"> ** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> JobRole </td>\n   <td style=\"text-align:right;\"> 86.19 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:right;\"> 0.0000000 </td>\n   <td style=\"text-align:right;\"> 0.2421 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> MaritalStatus </td>\n   <td style=\"text-align:right;\"> 46.16 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 0.0000000 </td>\n   <td style=\"text-align:right;\"> 0.1772 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> BusinessTravel </td>\n   <td style=\"text-align:right;\"> 24.18 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 0.0000056 </td>\n   <td style=\"text-align:right;\"> 0.1283 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Gender </td>\n   <td style=\"text-align:right;\"> 1.12 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 0.2905724 </td>\n   <td style=\"text-align:right;\"> 0.0276 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nOverTime and JobRole show the strongest relationships with attrition, both highly significant (p < 0.001) and exhibiting moderate effect sizes, suggesting that employees’ overtime status and job roles are meaningfully related to the likelihood of leaving the company. MaritalStatus and BusinessTravel are also highly significant, though with smaller effect sizes, indicating weaker but still relevant associations with attrition. Department shows a statistically significant relationship with attrition as well, but the small effect size suggests a limited practical impact. In contrast, Gender is not significantly associated with attrition, and its negligible effect size indicates that it is unlikely to influence whether an employee leaves the organization.\n\n## Numeric Variables Comparison\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 3: Distribution of Key Numeric Variables by Attrition Status](STAT515_HR_Attrition_FIXED_files/figure-html/numeric-comparison-1.png){width=960}\n:::\n:::\n\n\nWhen examining key numerical values in our analysis, we observe noticeable differences in attrition rates across employee categories. Attrition was more common among younger employees, those with lower monthly incomes, and employees with fewer years at the company. Additionally, employees who worked farther from home exhibited higher rates of attrition.\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Table 3: T-Tests Comparing Numeric Variables by Attrition Status</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">  </th>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> Mean (No) </th>\n   <th style=\"text-align:right;\"> Mean (Yes) </th>\n   <th style=\"text-align:right;\"> Difference </th>\n   <th style=\"text-align:right;\"> p-value </th>\n   <th style=\"text-align:left;\"> Sig. </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> mean in group No </td>\n   <td style=\"text-align:left;\"> Age </td>\n   <td style=\"text-align:right;\"> 37.56 </td>\n   <td style=\"text-align:right;\"> 33.61 </td>\n   <td style=\"text-align:right;\"> -3.95 </td>\n   <td style=\"text-align:right;\"> 0.0000000 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> mean in group No1 </td>\n   <td style=\"text-align:left;\"> MonthlyIncome </td>\n   <td style=\"text-align:right;\"> 6832.74 </td>\n   <td style=\"text-align:right;\"> 4787.09 </td>\n   <td style=\"text-align:right;\"> -2045.65 </td>\n   <td style=\"text-align:right;\"> 0.0000000 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> mean in group No2 </td>\n   <td style=\"text-align:left;\"> DistanceFromHome </td>\n   <td style=\"text-align:right;\"> 8.92 </td>\n   <td style=\"text-align:right;\"> 10.63 </td>\n   <td style=\"text-align:right;\"> 1.72 </td>\n   <td style=\"text-align:right;\"> 0.0041365 </td>\n   <td style=\"text-align:left;\"> ** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> mean in group No3 </td>\n   <td style=\"text-align:left;\"> YearsAtCompany </td>\n   <td style=\"text-align:right;\"> 7.37 </td>\n   <td style=\"text-align:right;\"> 5.13 </td>\n   <td style=\"text-align:right;\"> -2.24 </td>\n   <td style=\"text-align:right;\"> 0.0000002 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> mean in group No4 </td>\n   <td style=\"text-align:left;\"> YearsInCurrentRole </td>\n   <td style=\"text-align:right;\"> 4.48 </td>\n   <td style=\"text-align:right;\"> 2.90 </td>\n   <td style=\"text-align:right;\"> -1.58 </td>\n   <td style=\"text-align:right;\"> 0.0000000 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> mean in group No5 </td>\n   <td style=\"text-align:left;\"> YearsSinceLastPromotion </td>\n   <td style=\"text-align:right;\"> 2.23 </td>\n   <td style=\"text-align:right;\"> 1.95 </td>\n   <td style=\"text-align:right;\"> -0.29 </td>\n   <td style=\"text-align:right;\"> 0.1986513 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> mean in group No6 </td>\n   <td style=\"text-align:left;\"> TotalWorkingYears </td>\n   <td style=\"text-align:right;\"> 11.86 </td>\n   <td style=\"text-align:right;\"> 8.24 </td>\n   <td style=\"text-align:right;\"> -3.62 </td>\n   <td style=\"text-align:right;\"> 0.0000000 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> mean in group No7 </td>\n   <td style=\"text-align:left;\"> JobSatisfaction </td>\n   <td style=\"text-align:right;\"> 2.78 </td>\n   <td style=\"text-align:right;\"> 2.47 </td>\n   <td style=\"text-align:right;\"> -0.31 </td>\n   <td style=\"text-align:right;\"> 0.0001052 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> mean in group No8 </td>\n   <td style=\"text-align:left;\"> EnvironmentSatisfaction </td>\n   <td style=\"text-align:right;\"> 2.77 </td>\n   <td style=\"text-align:right;\"> 2.46 </td>\n   <td style=\"text-align:right;\"> -0.31 </td>\n   <td style=\"text-align:right;\"> 0.0002092 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> mean in group No9 </td>\n   <td style=\"text-align:left;\"> WorkLifeBalance </td>\n   <td style=\"text-align:right;\"> 2.78 </td>\n   <td style=\"text-align:right;\"> 2.66 </td>\n   <td style=\"text-align:right;\"> -0.12 </td>\n   <td style=\"text-align:right;\"> 0.0304657 </td>\n   <td style=\"text-align:left;\"> * </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Research Question 1\n## Work-Life Imbalance & Attrition Risk Profiling {.unnumbered}\n**How do work-life factors (OverTime, DistanceFromHome, WorkLifeBalance, YearsAtCompany) interact to predict employee attrition, and can we identify distinct \"high-risk\" employee profiles using these variables?**\n\n## Decision Tree Model\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 4: Decision Tree for Work-Life Attrition Risk Profiling](STAT515_HR_Attrition_FIXED_files/figure-html/q1-decision-tree-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 5: Decision Tree Feature Importance](STAT515_HR_Attrition_FIXED_files/figure-html/dt-importance-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction   0   1\n         0 249  21\n         1 119  52\n                                          \n               Accuracy : 0.6825          \n                 95% CI : (0.6368, 0.7258)\n    No Information Rate : 0.8345          \n    P-Value [Acc > NIR] : 1               \n                                          \n                  Kappa : 0.2529          \n                                          \n Mcnemar's Test P-Value : 2.444e-16       \n                                          \n            Sensitivity : 0.6766          \n            Specificity : 0.7123          \n         Pos Pred Value : 0.9222          \n         Neg Pred Value : 0.3041          \n             Prevalence : 0.8345          \n         Detection Rate : 0.5646          \n   Detection Prevalence : 0.6122          \n      Balanced Accuracy : 0.6945          \n                                          \n       'Positive' Class : 0               \n                                          \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nDecision Tree AUC-ROC: 0.7084 \n```\n\n\n:::\n:::\n\n\n## Logistic Regression with Interaction Terms\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Attrition_Binary ~ OverTime_Binary + DistanceFromHome + \n    WorkLifeBalance + YearsAtCompany + OT_x_WLB + OT_x_Distance + \n    OT_x_YearsAtCompany, family = binomial(link = \"logit\"), data = hr_q1)\n\nCoefficients:\n                    Estimate Std. Error z value Pr(>|z|)   \n(Intercept)         -1.14314    0.41339  -2.765  0.00569 **\nOverTime_Binary      0.89098    0.63757   1.397  0.16227   \nDistanceFromHome     0.01648    0.01195   1.380  0.16760   \nWorkLifeBalance     -0.30426    0.13679  -2.224  0.02613 * \nYearsAtCompany      -0.05304    0.02098  -2.528  0.01148 * \nOT_x_WLB             0.20612    0.20979   0.982  0.32586   \nOT_x_Distance        0.02246    0.01814   1.238  0.21561   \nOT_x_YearsAtCompany -0.06240    0.03301  -1.890  0.05875 . \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1298.6  on 1469  degrees of freedom\nResidual deviance: 1167.0  on 1462  degrees of freedom\nAIC: 1183\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Table 4: Logistic Regression Odds Ratios (Q1)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> β </th>\n   <th style=\"text-align:right;\"> OR </th>\n   <th style=\"text-align:right;\"> 95% CI Lower </th>\n   <th style=\"text-align:right;\"> 95% CI Upper </th>\n   <th style=\"text-align:right;\"> p-value </th>\n   <th style=\"text-align:left;\"> Sig. </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> OverTime_Binary </td>\n   <td style=\"text-align:right;\"> 0.8910 </td>\n   <td style=\"text-align:right;\"> 2.4375 </td>\n   <td style=\"text-align:right;\"> 0.6998 </td>\n   <td style=\"text-align:right;\"> 8.5502 </td>\n   <td style=\"text-align:right;\"> 0.1623 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> DistanceFromHome </td>\n   <td style=\"text-align:right;\"> 0.0165 </td>\n   <td style=\"text-align:right;\"> 1.0166 </td>\n   <td style=\"text-align:right;\"> 0.9926 </td>\n   <td style=\"text-align:right;\"> 1.0403 </td>\n   <td style=\"text-align:right;\"> 0.1676 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> WorkLifeBalance </td>\n   <td style=\"text-align:right;\"> -0.3043 </td>\n   <td style=\"text-align:right;\"> 0.7377 </td>\n   <td style=\"text-align:right;\"> 0.5653 </td>\n   <td style=\"text-align:right;\"> 0.9671 </td>\n   <td style=\"text-align:right;\"> 0.0261 </td>\n   <td style=\"text-align:left;\"> * </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> YearsAtCompany </td>\n   <td style=\"text-align:right;\"> -0.0530 </td>\n   <td style=\"text-align:right;\"> 0.9483 </td>\n   <td style=\"text-align:right;\"> 0.9081 </td>\n   <td style=\"text-align:right;\"> 0.9860 </td>\n   <td style=\"text-align:right;\"> 0.0115 </td>\n   <td style=\"text-align:left;\"> * </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> OT_x_WLB </td>\n   <td style=\"text-align:right;\"> 0.2061 </td>\n   <td style=\"text-align:right;\"> 1.2289 </td>\n   <td style=\"text-align:right;\"> 0.8137 </td>\n   <td style=\"text-align:right;\"> 1.8538 </td>\n   <td style=\"text-align:right;\"> 0.3259 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> OT_x_Distance </td>\n   <td style=\"text-align:right;\"> 0.0225 </td>\n   <td style=\"text-align:right;\"> 1.0227 </td>\n   <td style=\"text-align:right;\"> 0.9872 </td>\n   <td style=\"text-align:right;\"> 1.0600 </td>\n   <td style=\"text-align:right;\"> 0.2156 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> OT_x_YearsAtCompany </td>\n   <td style=\"text-align:right;\"> -0.0624 </td>\n   <td style=\"text-align:right;\"> 0.9395 </td>\n   <td style=\"text-align:right;\"> 0.8796 </td>\n   <td style=\"text-align:right;\"> 1.0016 </td>\n   <td style=\"text-align:right;\"> 0.0588 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Random Forest Model\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 6: Random Forest Variable Importance](STAT515_HR_Attrition_FIXED_files/figure-html/q1-random-forest-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 7: ROC Curves Comparison - Q1 Models](STAT515_HR_Attrition_FIXED_files/figure-html/q1-roc-comparison-1.png){width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Research Question 2\n## Career Stagnation & Compensation Effects {.unnumbered}\n\n**At what thresholds do career stagnation indicators (YearsSinceLastPromotion, YearsInCurrentRole) combined with compensation factors (MonthlyIncome, PercentSalaryHike) become critical predictors of attrition?**\n\n## Train/Test Split + Weighted Logistic Regression\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Attrition_Binary ~ YearsSinceLastPromotion + YearsInCurrentRole + \n    MonthlyIncome + PercentSalaryHike + JobLevel, family = binomial(), \n    data = train_q2, weights = weights_q2)\n\nCoefficients:\n                          Estimate Std. Error z value Pr(>|z|)    \n(Intercept)              1.757e+00  3.319e-01   5.293 1.20e-07 ***\nYearsSinceLastPromotion  1.428e-01  2.757e-02   5.180 2.22e-07 ***\nYearsInCurrentRole      -1.780e-01  2.683e-02  -6.635 3.24e-11 ***\nMonthlyIncome           -9.407e-05  5.010e-05  -1.878  0.06045 .  \nPercentSalaryHike       -5.107e-02  1.844e-02  -2.770  0.00561 ** \nJobLevel                -6.872e-02  2.009e-01  -0.342  0.73233    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1426.5  on 1028  degrees of freedom\nResidual deviance: 1309.6  on 1023  degrees of freedom\nAIC: 1740.9\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Table 5: Weighted Logistic Regression Odds Ratios (Q2)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> β </th>\n   <th style=\"text-align:right;\"> OR </th>\n   <th style=\"text-align:right;\"> 95% CI Lower </th>\n   <th style=\"text-align:right;\"> 95% CI Upper </th>\n   <th style=\"text-align:right;\"> p-value </th>\n   <th style=\"text-align:left;\"> Sig. </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> YearsSinceLastPromotion </td>\n   <td style=\"text-align:right;\"> 0.1428 </td>\n   <td style=\"text-align:right;\"> 1.1535 </td>\n   <td style=\"text-align:right;\"> 1.0935 </td>\n   <td style=\"text-align:right;\"> 1.2185 </td>\n   <td style=\"text-align:right;\"> 0.0000 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> YearsInCurrentRole </td>\n   <td style=\"text-align:right;\"> -0.1780 </td>\n   <td style=\"text-align:right;\"> 0.8369 </td>\n   <td style=\"text-align:right;\"> 0.7933 </td>\n   <td style=\"text-align:right;\"> 0.8814 </td>\n   <td style=\"text-align:right;\"> 0.0000 </td>\n   <td style=\"text-align:left;\"> *** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> MonthlyIncome </td>\n   <td style=\"text-align:right;\"> -0.0001 </td>\n   <td style=\"text-align:right;\"> 0.9999 </td>\n   <td style=\"text-align:right;\"> 0.9998 </td>\n   <td style=\"text-align:right;\"> 1.0000 </td>\n   <td style=\"text-align:right;\"> 0.0604 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> PercentSalaryHike </td>\n   <td style=\"text-align:right;\"> -0.0511 </td>\n   <td style=\"text-align:right;\"> 0.9502 </td>\n   <td style=\"text-align:right;\"> 0.9163 </td>\n   <td style=\"text-align:right;\"> 0.9850 </td>\n   <td style=\"text-align:right;\"> 0.0056 </td>\n   <td style=\"text-align:left;\"> ** </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> JobLevel </td>\n   <td style=\"text-align:right;\"> -0.0687 </td>\n   <td style=\"text-align:right;\"> 0.9336 </td>\n   <td style=\"text-align:right;\"> 0.6297 </td>\n   <td style=\"text-align:right;\"> 1.3855 </td>\n   <td style=\"text-align:right;\"> 0.7323 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## LASSO Variable Selection\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 8: LASSO Cross-Validation](STAT515_HR_Attrition_FIXED_files/figure-html/q2-lasso-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 9: LASSO Selected Variable Coefficients](STAT515_HR_Attrition_FIXED_files/figure-html/lasso-coefficients-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Table 6: LASSO Selected Variables</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> Coefficient </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> OverTime_Binary </td>\n   <td style=\"text-align:right;\"> 1.6306 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> StockOptionLevel </td>\n   <td style=\"text-align:right;\"> -0.5456 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> EnvironmentSatisfaction </td>\n   <td style=\"text-align:right;\"> -0.3751 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> JobSatisfaction </td>\n   <td style=\"text-align:right;\"> -0.3263 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> WorkLifeBalance </td>\n   <td style=\"text-align:right;\"> -0.2454 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> YearsSinceLastPromotion </td>\n   <td style=\"text-align:right;\"> 0.1537 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> NumCompaniesWorked </td>\n   <td style=\"text-align:right;\"> 0.1486 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> YearsInCurrentRole </td>\n   <td style=\"text-align:right;\"> -0.1228 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> YearsWithCurrManager </td>\n   <td style=\"text-align:right;\"> -0.1221 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> JobLevel </td>\n   <td style=\"text-align:right;\"> -0.0816 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> YearsAtCompany </td>\n   <td style=\"text-align:right;\"> 0.0723 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> TotalWorkingYears </td>\n   <td style=\"text-align:right;\"> -0.0478 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Age </td>\n   <td style=\"text-align:right;\"> -0.0364 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> DistanceFromHome </td>\n   <td style=\"text-align:right;\"> 0.0348 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> PercentSalaryHike </td>\n   <td style=\"text-align:right;\"> -0.0159 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## ROC-AUC and Threshold Analysis (Test Set)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 10: ROC Curve and Threshold Analysis (Test Set)](STAT515_HR_Attrition_FIXED_files/figure-html/q2-roc-threshold-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Table 7: Classification Performance at Different Thresholds (Test Set)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> Threshold </th>\n   <th style=\"text-align:right;\"> Sensitivity </th>\n   <th style=\"text-align:right;\"> Specificity </th>\n   <th style=\"text-align:right;\"> Accuracy </th>\n   <th style=\"text-align:left;\"> Note </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 0.100 </td>\n   <td style=\"text-align:right;\"> 0.973 </td>\n   <td style=\"text-align:right;\"> 0.043 </td>\n   <td style=\"text-align:right;\"> 0.197 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 0.200 </td>\n   <td style=\"text-align:right;\"> 0.959 </td>\n   <td style=\"text-align:right;\"> 0.117 </td>\n   <td style=\"text-align:right;\"> 0.256 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 0.300 </td>\n   <td style=\"text-align:right;\"> 0.918 </td>\n   <td style=\"text-align:right;\"> 0.283 </td>\n   <td style=\"text-align:right;\"> 0.388 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 0.400 </td>\n   <td style=\"text-align:right;\"> 0.781 </td>\n   <td style=\"text-align:right;\"> 0.413 </td>\n   <td style=\"text-align:right;\"> 0.474 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 0.500 </td>\n   <td style=\"text-align:right;\"> 0.699 </td>\n   <td style=\"text-align:right;\"> 0.562 </td>\n   <td style=\"text-align:right;\"> 0.585 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;font-weight: bold;background-color: rgba(212, 237, 218, 255) !important;\"> 0.574 </td>\n   <td style=\"text-align:right;font-weight: bold;background-color: rgba(212, 237, 218, 255) !important;\"> 0.589 </td>\n   <td style=\"text-align:right;font-weight: bold;background-color: rgba(212, 237, 218, 255) !important;\"> 0.728 </td>\n   <td style=\"text-align:right;font-weight: bold;background-color: rgba(212, 237, 218, 255) !important;\"> 0.705 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(212, 237, 218, 255) !important;\"> ← Optimal (Youden's J) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Research Question 3\n## Department-Stratified Satisfaction Analysis {.unnumbered}\n\n**Does the predictive power of employee satisfaction variables differ across departments?**\n\n## VIF Analysis for Multicollinearity\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Table 8: Variance Inflation Factors (VIF)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> VIF </th>\n   <th style=\"text-align:left;\"> Status </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> JobSatisfaction </td>\n   <td style=\"text-align:right;\"> 1.0011 </td>\n   <td style=\"text-align:left;\"> OK </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> EnvironmentSatisfaction </td>\n   <td style=\"text-align:right;\"> 1.0012 </td>\n   <td style=\"text-align:left;\"> OK </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> RelationshipSatisfaction </td>\n   <td style=\"text-align:right;\"> 1.0046 </td>\n   <td style=\"text-align:left;\"> OK </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> WorkLifeBalance </td>\n   <td style=\"text-align:right;\"> 1.0045 </td>\n   <td style=\"text-align:left;\"> OK </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> JobInvolvement </td>\n   <td style=\"text-align:right;\"> 1.0039 </td>\n   <td style=\"text-align:left;\"> OK </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> MonthlyIncome </td>\n   <td style=\"text-align:right;\"> 1.3345 </td>\n   <td style=\"text-align:left;\"> OK </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Age </td>\n   <td style=\"text-align:right;\"> 1.3376 </td>\n   <td style=\"text-align:left;\"> OK </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n<span style=\"color: orange; font-weight: bold;\">Why are these 7 variables being selected for VIF? I get the 3 satisfaction variables because they were mentioned in the data set description as being used for question 3, but why the others? There are a lot of outputs in the project, but I'm not sure why the specific variables or methods were chosen</span>\n\nThe Variance Inflation Factor (VIF) analysis for the selected variables indicates that there is no evidence of multicollinearity among the independent variables included in the model. All VIF values are very close to 1, ranging from approximately 1.00 to 1.34, which suggests that each predictor has minimal correlation with the others. Since all values are well below commonly accepted thresholds (such as 5 or 10), multicollinearity is not a concern in this analysis. Therefore, all variables can be retained in the model without risk of inflated standard errors or unstable coefficient estimates.\n\n## Stratified Logistic Regression by Department\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n========================================\nDEPARTMENT: HR \n========================================\nSample Size: 63 \nAttrition Rate: 19 %\n\nCall:\nglm(formula = Attrition_Binary ~ JobSatisfaction + EnvironmentSatisfaction + \n    RelationshipSatisfaction, family = binomial(), data = df_dept)\n\nCoefficients:\n                         Estimate Std. Error z value Pr(>|z|)\n(Intercept)                0.1371     1.5933   0.086    0.931\nJobSatisfaction           -0.5074     0.3211  -1.580    0.114\nEnvironmentSatisfaction   -0.3877     0.3239  -1.197    0.231\nRelationshipSatisfaction   0.2198     0.3434   0.640    0.522\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 61.351  on 62  degrees of freedom\nResidual deviance: 56.601  on 59  degrees of freedom\nAIC: 64.601\n\nNumber of Fisher Scoring iterations: 4\n\n\n========================================\nDEPARTMENT: R&D \n========================================\nSample Size: 961 \nAttrition Rate: 13.8 %\n\nCall:\nglm(formula = Attrition_Binary ~ JobSatisfaction + EnvironmentSatisfaction + \n    RelationshipSatisfaction, family = binomial(), data = df_dept)\n\nCoefficients:\n                         Estimate Std. Error z value Pr(>|z|)   \n(Intercept)               0.05548    0.39463   0.141  0.88820   \nJobSatisfaction          -0.26624    0.08489  -3.136  0.00171 **\nEnvironmentSatisfaction  -0.25997    0.08450  -3.077  0.00209 **\nRelationshipSatisfaction -0.19146    0.08718  -2.196  0.02809 * \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 772.73  on 960  degrees of freedom\nResidual deviance: 749.18  on 957  degrees of freedom\nAIC: 757.18\n\nNumber of Fisher Scoring iterations: 4\n\n\n========================================\nDEPARTMENT: Sales \n========================================\nSample Size: 446 \nAttrition Rate: 20.6 %\n\nCall:\nglm(formula = Attrition_Binary ~ JobSatisfaction + EnvironmentSatisfaction + \n    RelationshipSatisfaction, family = binomial(), data = df_dept)\n\nCoefficients:\n                         Estimate Std. Error z value Pr(>|z|)  \n(Intercept)              -0.03132    0.49683  -0.063   0.9497  \nJobSatisfaction          -0.22829    0.10514  -2.171   0.0299 *\nEnvironmentSatisfaction  -0.22291    0.10875  -2.050   0.0404 *\nRelationshipSatisfaction -0.04758    0.10540  -0.451   0.6517  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 454.01  on 445  degrees of freedom\nResidual deviance: 444.72  on 442  degrees of freedom\nAIC: 452.72\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 11: Satisfaction Variable Coefficients by Department](STAT515_HR_Attrition_FIXED_files/figure-html/q3-coefficient-comparison-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Table 9: Department Model Comparison</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Department </th>\n   <th style=\"text-align:right;\"> N </th>\n   <th style=\"text-align:right;\"> Attrition Rate (%) </th>\n   <th style=\"text-align:right;\"> AIC </th>\n   <th style=\"text-align:right;\"> AUC </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> HR </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 19.0 </td>\n   <td style=\"text-align:right;\"> 64.60 </td>\n   <td style=\"text-align:right;\"> 0.679 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> R&amp;D </td>\n   <td style=\"text-align:right;\"> 961 </td>\n   <td style=\"text-align:right;\"> 13.8 </td>\n   <td style=\"text-align:right;\"> 757.18 </td>\n   <td style=\"text-align:right;\"> 0.616 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Sales </td>\n   <td style=\"text-align:right;\"> 446 </td>\n   <td style=\"text-align:right;\"> 20.6 </td>\n   <td style=\"text-align:right;\"> 452.72 </td>\n   <td style=\"text-align:right;\"> 0.597 </td>\n  </tr>\n</tbody>\n</table>\n\n\n\nFigure 12: Model Performance by Department\n:::\n:::\n\n\n------------------------------------------------------------------------\n\nThe stratified logistic regression results reveal notable differences across departments in how satisfaction metrics relate to attrition.\n\nIn the HR department (n = 63, 19% attrition), none of the predictors (JobSatisfaction, EnvironmentSatisfaction, or RelationshipSatisfaction) are statistically significant, likely due to the small sample size, though the output suggests that higher job and environment satisfaction ratings could reduce attrition.\n\nIn R&D (n = 961, 13.8% attrition), all three satisfaction measures are significant predictors: higher job, environment, and relationship satisfaction are associated with lower attrition, with job and environment satisfaction having the strongest effects. \nIn Sales (n = 446, 20.6% attrition), job and environment satisfaction significantly reduce attrition, while relationship satisfaction is not significant. Overall, the results suggest that the effect of satisfaction on attrition varies by department.\n\nR&D appears most sensitive to satisfaction levels, with Sales being moderately sensitive, and HR shows no clear patterns, likely reflecting limited sample size or unmeasured factors. These findings indicate that department-specific strategies—focusing on improving job and environment satisfaction—could be most effective in reducing turnover, while HR may require a broader analysis of attrition drivers.\n\n------------------------------------------------------------------------\n\n# Discussion and Conclusions\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n=============================================\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSUMMARY STATISTICS\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=============================================\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal Employees Analyzed: 1470 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOverall Attrition Rate: 16.1 %\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOverTime Attrition Rate: 30.5 %\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNon-OverTime Attrition Rate: 10.4 %\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBest Model Performance:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Random Forest AUC (Q1): 0.619 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Weighted LR AUC (Q2 test): 0.665 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- Optimal Threshold (Q2 test): 0.574 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n- LASSO Variables Selected: 15 of 16\n```\n\n\n:::\n:::\n\n\n## Recommendations for HR Practice\n\n1.  **Monitor Overtime:** Overtime is consistently among the strongest predictors of attrition.\n2.  **Promotion Cadence:** Stagnation signals (especially time since last promotion) meaningfully shift attrition risk.\n3.  **Department-Specific Actions:** Satisfaction signals and their strengths differ by department.\n\n## Limitations\n\nDue to employee and corporate confidentiality concerns, publicly available datasets containing detailed employee information are limited. While the dataset used in this project serves as a realistic approximation of HR records for a large organization and can inform analyses and decision-making strategies relevant to real-world company data, it is still a synthetic dataset.\n\nClass imbalance within the dataset presented analytical challenges. Employee attrition, being a minority class, required careful threshold adjustments to ensure sensitivity and avoid biased predictive outcomes.\n\nThe dataset did not include information regarding the reasons for employee departures. Distinguishing between voluntary resignations and terminations could have allowed for more targeted analyses, such as identifying employees the company might have retained versus those who were dismissed.\n\nThe dataset represents a cross-sectional snapshot, which allows for the identification of associations but not causal relationships. Factors influencing attrition may vary significantly among individual employees, limiting the ability to draw definitive causal conclusions.\n\n------------------------------------------------------------------------\n\n# References\n\n1.  IBM HR Analytics Employee Attrition Dataset. Available at: https://data.world/aaizemberg/hr-employee-attrition\\\n2.  James, G., Witten, D., Hastie, T., & Tibshirani, R. (2021). *An Introduction to Statistical Learning (2nd ed.).* Springer.\\\n3.  Hosmer, D. W., Lemeshow, S., & Sturdivant, R. X. (2013). *Applied Logistic Regression (3rd ed.).* Wiley.\\\n4.  Breiman, L. (2001). Random Forests. *Machine Learning, 45*(1), 5–32.\\\n5.  Tibshirani, R. (1996). Regression Shrinkage and Selection via the Lasso. *JRSS Series B, 58*(1), 267–288.\\\n6.  R Core Team. (2024). *R: A Language and Environment for Statistical Computing.*\n\n------------------------------------------------------------------------\n\n# Appendix: Session Information\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.1 (2025-06-13 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: America/New_York\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] rlang_1.1.6          gridExtra_2.3        pROC_1.19.0.1       \n [4] glmnet_4.1-10        Matrix_1.7-3         randomForest_4.7-1.2\n [7] rpart.plot_3.1.3     rpart_4.1.24         caret_7.0-1         \n[10] lattice_0.22-7       car_3.1-3            carData_3.0-5       \n[13] corrplot_0.95        scales_1.4.0         kableExtra_1.4.0    \n[16] knitr_1.50           tidyr_1.3.1          ggplot2_3.5.2       \n[19] dplyr_1.1.4          readxl_1.4.5        \n\nloaded via a namespace (and not attached):\n [1] tidyselect_1.2.1     viridisLite_0.4.2    timeDate_4051.111   \n [4] farver_2.1.2         fastmap_1.2.0        digest_0.6.37       \n [7] timechange_0.3.0     lifecycle_1.0.4      survival_3.8-3      \n[10] magrittr_2.0.3       compiler_4.5.1       tools_4.5.1         \n[13] yaml_2.3.10          data.table_1.17.8    labeling_0.4.3      \n[16] htmlwidgets_1.6.4    plyr_1.8.9           xml2_1.4.0          \n[19] RColorBrewer_1.1-3   abind_1.4-8          withr_3.0.2         \n[22] purrr_1.1.0          stats4_4.5.1         nnet_7.3-20         \n[25] grid_4.5.1           e1071_1.7-16         future_1.68.0       \n[28] globals_0.18.0       iterators_1.0.14     MASS_7.3-65         \n[31] dichromat_2.0-0.1    cli_3.6.5            rmarkdown_2.29      \n[34] generics_0.1.4       rstudioapi_0.17.1    future.apply_1.20.0 \n[37] reshape2_1.4.5       proxy_0.4-27         stringr_1.5.2       \n[40] splines_4.5.1        parallel_4.5.1       cellranger_1.1.0    \n[43] vctrs_0.6.5          hardhat_1.4.2        jsonlite_2.0.0      \n[46] Formula_1.2-5        listenv_0.10.0       systemfonts_1.3.1   \n[49] foreach_1.5.2        gower_1.0.2          recipes_1.3.1       \n[52] glue_1.8.0           parallelly_1.45.1    codetools_0.2-20    \n[55] shape_1.4.6.1        lubridate_1.9.4      stringi_1.8.7       \n[58] gtable_0.3.6         tibble_3.3.0         pillar_1.11.0       \n[61] htmltools_0.5.8.1    ipred_0.9-15         lava_1.8.2          \n[64] R6_2.6.1             textshaping_1.0.3    evaluate_1.0.5      \n[67] class_7.3-23         Rcpp_1.1.0           svglite_2.2.2       \n[70] nlme_3.1-168         prodlim_2025.04.28   xfun_0.52           \n[73] pkgconfig_2.0.3      ModelMetrics_1.2.2.2\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "STAT515_HR_Attrition_FIXED_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}